# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

DN_HistogramMode_5 <- function(x) {
    .Call(`_catch22_DN_HistogramMode_5`, x)
}

DN_HistogramMode_10 <- function(x) {
    .Call(`_catch22_DN_HistogramMode_10`, x)
}

CO_f1ecac <- function(x) {
    .Call(`_catch22_CO_f1ecac`, x)
}

CO_FirstMin_ac <- function(x) {
    .Call(`_catch22_CO_FirstMin_ac`, x)
}

CO_HistogramAMI_even_2_5 <- function(x) {
    .Call(`_catch22_CO_HistogramAMI_even_2_5`, x)
}

CO_trev_1_num <- function(x) {
    .Call(`_catch22_CO_trev_1_num`, x)
}

MD_hrv_classic_pnn40 <- function(x) {
    .Call(`_catch22_MD_hrv_classic_pnn40`, x)
}

SB_BinaryStats_mean_longstretch1 <- function(x) {
    .Call(`_catch22_SB_BinaryStats_mean_longstretch1`, x)
}

SB_TransitionMatrix_3ac_sumdiagcov <- function(x) {
    .Call(`_catch22_SB_TransitionMatrix_3ac_sumdiagcov`, x)
}

PD_PeriodicityWang_th0_01 <- function(x) {
    .Call(`_catch22_PD_PeriodicityWang_th0_01`, x)
}

CO_Embed2_Dist_tau_d_expfit_meandiff <- function(x) {
    .Call(`_catch22_CO_Embed2_Dist_tau_d_expfit_meandiff`, x)
}

IN_AutoMutualInfoStats_40_gaussian_fmmi <- function(x) {
    .Call(`_catch22_IN_AutoMutualInfoStats_40_gaussian_fmmi`, x)
}

FC_LocalSimple_mean1_tauresrat <- function(x) {
    .Call(`_catch22_FC_LocalSimple_mean1_tauresrat`, x)
}

DN_OutlierInclude_p_001_mdrmd <- function(x) {
    .Call(`_catch22_DN_OutlierInclude_p_001_mdrmd`, x)
}

DN_OutlierInclude_n_001_mdrmd <- function(x) {
    .Call(`_catch22_DN_OutlierInclude_n_001_mdrmd`, x)
}

SP_Summaries_welch_rect_area_5_1 <- function(x) {
    .Call(`_catch22_SP_Summaries_welch_rect_area_5_1`, x)
}

SB_BinaryStats_diff_longstretch0 <- function(x) {
    .Call(`_catch22_SB_BinaryStats_diff_longstretch0`, x)
}

SB_MotifThree_quantile_hh <- function(x) {
    .Call(`_catch22_SB_MotifThree_quantile_hh`, x)
}

SC_FluctAnal_2_rsrangefit_50_1_logi_prop_r1 <- function(x) {
    .Call(`_catch22_SC_FluctAnal_2_rsrangefit_50_1_logi_prop_r1`, x)
}

SC_FluctAnal_2_dfa_50_1_2_logi_prop_r1 <- function(x) {
    .Call(`_catch22_SC_FluctAnal_2_dfa_50_1_2_logi_prop_r1`, x)
}

SP_Summaries_welch_rect_centroid <- function(x) {
    .Call(`_catch22_SP_Summaries_welch_rect_centroid`, x)
}

FC_LocalSimple_mean3_stderr <- function(x) {
    .Call(`_catch22_FC_LocalSimple_mean3_stderr`, x)
}

