function [featureValues, featureNames] = catch22_all(data, doCatch24)
% catch22_all   Calculate all catch22 (or catch24) features from an input time series
%
% ---INPUTS
% data: a univariate time series (row vector)
% catch24: set to true to also include mean and standard deviation (a total of 24
%               features)
% ---OUTPUTS:
% featureValues: computed feature values for the input data

%-------------------------------------------------------------------------------
%% Check inputs and set defaults
%-------------------------------------------------------------------------------
if nargin < 2
    doCatch24 = false;
end

%-------------------------------------------------------------------------------
% Define the features:
%-------------------------------------------------------------------------------

% catch22:
featureNames = ...
{ ...
'DN_HistogramMode_5', ...
'DN_HistogramMode_10', ...
'CO_f1ecac', ...
'CO_FirstMin_ac', ...
'CO_HistogramAMI_even_2_5', ...
'CO_trev_1_num', ...
'MD_hrv_classic_pnn40', ...
'SB_BinaryStats_mean_longstretch1', ...
'SB_TransitionMatrix_3ac_sumdiagcov', ...
'PD_PeriodicityWang_th0_01', ...
'CO_Embed2_Dist_tau_d_expfit_meandiff', ...
'IN_AutoMutualInfoStats_40_gaussian_fmmi', ...
'FC_LocalSimple_mean1_tauresrat', ...
'DN_OutlierInclude_p_001_mdrmd', ...
'DN_OutlierInclude_n_001_mdrmd', ...
'SP_Summaries_welch_rect_area_5_1', ...
'SB_BinaryStats_diff_longstretch0', ...
'SB_MotifThree_quantile_hh', ...
'SC_FluctAnal_2_rsrangefit_50_1_logi_prop_r1', ...
'SC_FluctAnal_2_dfa_50_1_2_logi_prop_r1', ...
'SP_Summaries_welch_rect_centroid', ...
'FC_LocalSimple_mean3_stderr'
};

% Add basic properties of the distribution (mean and standard deviation) as catch24 if desired:
if doCatch24
    additionals = {'DN_Mean', 'DN_Spread_Std'};
    featureNames = [featureNames, additionals];
end

%-------------------------------------------------------------------------------
% Compute all features from their local catch22 (compiled) implementations
%-------------------------------------------------------------------------------
numFeatures = length(featureNames);
featureValues = zeros(numFeatures,1);

for featureInd = 1:numFeatures
    featureName = featureNames{featureInd};
    fh = str2func(['catch22_', featureName]);
    featureValues(featureInd) = fh(data');
end

end
