// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// DN_HistogramMode_5
NumericVector DN_HistogramMode_5(NumericVector x);
RcppExport SEXP _catch22_DN_HistogramMode_5(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(DN_HistogramMode_5(x));
    return rcpp_result_gen;
END_RCPP
}
// DN_HistogramMode_10
NumericVector DN_HistogramMode_10(NumericVector x);
RcppExport SEXP _catch22_DN_HistogramMode_10(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(DN_HistogramMode_10(x));
    return rcpp_result_gen;
END_RCPP
}
// CO_f1ecac
NumericVector CO_f1ecac(NumericVector x);
RcppExport SEXP _catch22_CO_f1ecac(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(CO_f1ecac(x));
    return rcpp_result_gen;
END_RCPP
}
// CO_FirstMin_ac
NumericVector CO_FirstMin_ac(NumericVector x);
RcppExport SEXP _catch22_CO_FirstMin_ac(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(CO_FirstMin_ac(x));
    return rcpp_result_gen;
END_RCPP
}
// CO_HistogramAMI_even_2_5
NumericVector CO_HistogramAMI_even_2_5(NumericVector x);
RcppExport SEXP _catch22_CO_HistogramAMI_even_2_5(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(CO_HistogramAMI_even_2_5(x));
    return rcpp_result_gen;
END_RCPP
}
// CO_trev_1_num
NumericVector CO_trev_1_num(NumericVector x);
RcppExport SEXP _catch22_CO_trev_1_num(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(CO_trev_1_num(x));
    return rcpp_result_gen;
END_RCPP
}
// MD_hrv_classic_pnn40
NumericVector MD_hrv_classic_pnn40(NumericVector x);
RcppExport SEXP _catch22_MD_hrv_classic_pnn40(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(MD_hrv_classic_pnn40(x));
    return rcpp_result_gen;
END_RCPP
}
// SB_BinaryStats_mean_longstretch1
NumericVector SB_BinaryStats_mean_longstretch1(NumericVector x);
RcppExport SEXP _catch22_SB_BinaryStats_mean_longstretch1(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(SB_BinaryStats_mean_longstretch1(x));
    return rcpp_result_gen;
END_RCPP
}
// SB_TransitionMatrix_3ac_sumdiagcov
NumericVector SB_TransitionMatrix_3ac_sumdiagcov(NumericVector x);
RcppExport SEXP _catch22_SB_TransitionMatrix_3ac_sumdiagcov(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(SB_TransitionMatrix_3ac_sumdiagcov(x));
    return rcpp_result_gen;
END_RCPP
}
// PD_PeriodicityWang_th0_01
NumericVector PD_PeriodicityWang_th0_01(NumericVector x);
RcppExport SEXP _catch22_PD_PeriodicityWang_th0_01(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(PD_PeriodicityWang_th0_01(x));
    return rcpp_result_gen;
END_RCPP
}
// CO_Embed2_Dist_tau_d_expfit_meandiff
NumericVector CO_Embed2_Dist_tau_d_expfit_meandiff(NumericVector x);
RcppExport SEXP _catch22_CO_Embed2_Dist_tau_d_expfit_meandiff(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(CO_Embed2_Dist_tau_d_expfit_meandiff(x));
    return rcpp_result_gen;
END_RCPP
}
// IN_AutoMutualInfoStats_40_gaussian_fmmi
NumericVector IN_AutoMutualInfoStats_40_gaussian_fmmi(NumericVector x);
RcppExport SEXP _catch22_IN_AutoMutualInfoStats_40_gaussian_fmmi(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(IN_AutoMutualInfoStats_40_gaussian_fmmi(x));
    return rcpp_result_gen;
END_RCPP
}
// FC_LocalSimple_mean1_tauresrat
NumericVector FC_LocalSimple_mean1_tauresrat(NumericVector x);
RcppExport SEXP _catch22_FC_LocalSimple_mean1_tauresrat(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(FC_LocalSimple_mean1_tauresrat(x));
    return rcpp_result_gen;
END_RCPP
}
// DN_OutlierInclude_p_001_mdrmd
NumericVector DN_OutlierInclude_p_001_mdrmd(NumericVector x);
RcppExport SEXP _catch22_DN_OutlierInclude_p_001_mdrmd(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(DN_OutlierInclude_p_001_mdrmd(x));
    return rcpp_result_gen;
END_RCPP
}
// DN_OutlierInclude_n_001_mdrmd
NumericVector DN_OutlierInclude_n_001_mdrmd(NumericVector x);
RcppExport SEXP _catch22_DN_OutlierInclude_n_001_mdrmd(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(DN_OutlierInclude_n_001_mdrmd(x));
    return rcpp_result_gen;
END_RCPP
}
// SP_Summaries_welch_rect_area_5_1
NumericVector SP_Summaries_welch_rect_area_5_1(NumericVector x);
RcppExport SEXP _catch22_SP_Summaries_welch_rect_area_5_1(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(SP_Summaries_welch_rect_area_5_1(x));
    return rcpp_result_gen;
END_RCPP
}
// SB_BinaryStats_diff_longstretch0
NumericVector SB_BinaryStats_diff_longstretch0(NumericVector x);
RcppExport SEXP _catch22_SB_BinaryStats_diff_longstretch0(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(SB_BinaryStats_diff_longstretch0(x));
    return rcpp_result_gen;
END_RCPP
}
// SB_MotifThree_quantile_hh
NumericVector SB_MotifThree_quantile_hh(NumericVector x);
RcppExport SEXP _catch22_SB_MotifThree_quantile_hh(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(SB_MotifThree_quantile_hh(x));
    return rcpp_result_gen;
END_RCPP
}
// SC_FluctAnal_2_rsrangefit_50_1_logi_prop_r1
NumericVector SC_FluctAnal_2_rsrangefit_50_1_logi_prop_r1(NumericVector x);
RcppExport SEXP _catch22_SC_FluctAnal_2_rsrangefit_50_1_logi_prop_r1(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(SC_FluctAnal_2_rsrangefit_50_1_logi_prop_r1(x));
    return rcpp_result_gen;
END_RCPP
}
// SC_FluctAnal_2_dfa_50_1_2_logi_prop_r1
NumericVector SC_FluctAnal_2_dfa_50_1_2_logi_prop_r1(NumericVector x);
RcppExport SEXP _catch22_SC_FluctAnal_2_dfa_50_1_2_logi_prop_r1(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(SC_FluctAnal_2_dfa_50_1_2_logi_prop_r1(x));
    return rcpp_result_gen;
END_RCPP
}
// SP_Summaries_welch_rect_centroid
NumericVector SP_Summaries_welch_rect_centroid(NumericVector x);
RcppExport SEXP _catch22_SP_Summaries_welch_rect_centroid(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(SP_Summaries_welch_rect_centroid(x));
    return rcpp_result_gen;
END_RCPP
}
// FC_LocalSimple_mean3_stderr
NumericVector FC_LocalSimple_mean3_stderr(NumericVector x);
RcppExport SEXP _catch22_FC_LocalSimple_mean3_stderr(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(FC_LocalSimple_mean3_stderr(x));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_catch22_DN_HistogramMode_5", (DL_FUNC) &_catch22_DN_HistogramMode_5, 1},
    {"_catch22_DN_HistogramMode_10", (DL_FUNC) &_catch22_DN_HistogramMode_10, 1},
    {"_catch22_CO_f1ecac", (DL_FUNC) &_catch22_CO_f1ecac, 1},
    {"_catch22_CO_FirstMin_ac", (DL_FUNC) &_catch22_CO_FirstMin_ac, 1},
    {"_catch22_CO_HistogramAMI_even_2_5", (DL_FUNC) &_catch22_CO_HistogramAMI_even_2_5, 1},
    {"_catch22_CO_trev_1_num", (DL_FUNC) &_catch22_CO_trev_1_num, 1},
    {"_catch22_MD_hrv_classic_pnn40", (DL_FUNC) &_catch22_MD_hrv_classic_pnn40, 1},
    {"_catch22_SB_BinaryStats_mean_longstretch1", (DL_FUNC) &_catch22_SB_BinaryStats_mean_longstretch1, 1},
    {"_catch22_SB_TransitionMatrix_3ac_sumdiagcov", (DL_FUNC) &_catch22_SB_TransitionMatrix_3ac_sumdiagcov, 1},
    {"_catch22_PD_PeriodicityWang_th0_01", (DL_FUNC) &_catch22_PD_PeriodicityWang_th0_01, 1},
    {"_catch22_CO_Embed2_Dist_tau_d_expfit_meandiff", (DL_FUNC) &_catch22_CO_Embed2_Dist_tau_d_expfit_meandiff, 1},
    {"_catch22_IN_AutoMutualInfoStats_40_gaussian_fmmi", (DL_FUNC) &_catch22_IN_AutoMutualInfoStats_40_gaussian_fmmi, 1},
    {"_catch22_FC_LocalSimple_mean1_tauresrat", (DL_FUNC) &_catch22_FC_LocalSimple_mean1_tauresrat, 1},
    {"_catch22_DN_OutlierInclude_p_001_mdrmd", (DL_FUNC) &_catch22_DN_OutlierInclude_p_001_mdrmd, 1},
    {"_catch22_DN_OutlierInclude_n_001_mdrmd", (DL_FUNC) &_catch22_DN_OutlierInclude_n_001_mdrmd, 1},
    {"_catch22_SP_Summaries_welch_rect_area_5_1", (DL_FUNC) &_catch22_SP_Summaries_welch_rect_area_5_1, 1},
    {"_catch22_SB_BinaryStats_diff_longstretch0", (DL_FUNC) &_catch22_SB_BinaryStats_diff_longstretch0, 1},
    {"_catch22_SB_MotifThree_quantile_hh", (DL_FUNC) &_catch22_SB_MotifThree_quantile_hh, 1},
    {"_catch22_SC_FluctAnal_2_rsrangefit_50_1_logi_prop_r1", (DL_FUNC) &_catch22_SC_FluctAnal_2_rsrangefit_50_1_logi_prop_r1, 1},
    {"_catch22_SC_FluctAnal_2_dfa_50_1_2_logi_prop_r1", (DL_FUNC) &_catch22_SC_FluctAnal_2_dfa_50_1_2_logi_prop_r1, 1},
    {"_catch22_SP_Summaries_welch_rect_centroid", (DL_FUNC) &_catch22_SP_Summaries_welch_rect_centroid, 1},
    {"_catch22_FC_LocalSimple_mean3_stderr", (DL_FUNC) &_catch22_FC_LocalSimple_mean3_stderr, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_catch22(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
